### ISSUE TITLE
Can you please share the config file for particular namespace like say test

### ISSUE THREAD

**Issue by AkshayDubey29** [bitnami/bitnami-docker-kubewatch#3]
Can you please share the config file for particular namespace like say test?

**Comment by alemorcuq** [comment]
Hi, @AkshayDubey29.

In order to watch a particular namespace (for example, `test`) you can specify in your config file like this:

```
handler:
  slack:
    token: YOUR_SLACK_TOKEN
    channel: YOUR_SLACK_CHANNEL
resource:
  deployment: false
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: true
  pod: true
  secret: false
  configmap: false
  ingress: false
namespace: test
```

You can check all the configuration options at kubewatch's repo: https://github.com/bitnami-labs/kubewatch#viewing-config
